package Interface;

import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import pkgLocadora.Game;


public class TelaPrincipal extends javax.swing.JFrame {

    Game GamePrincipal = new Game();

    public Game getGamePrincipal() {
        return GamePrincipal;
    }

    public void setSGamePrincipal(Game GamePrincipal) {
        this.GamePrincipal = GamePrincipal;
    }


    /**
     * Creates new form NovoJFrame1
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonCadastrarOperador = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAdicionarOperador = new javax.swing.JMenuItem();
        jMenuItemTrocarOperador = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemCadastrarCliente = new javax.swing.JMenuItem();
        jMenuItemRemoverCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemCadastrarJogos = new javax.swing.JMenuItem();
        jMenuItemBuscarJogos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemLocacao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game");
        setLocation(new java.awt.Point(180, 180));

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));

        jLabel1.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jLabel1.setText("                   Bem Vindo!");

        jLabel3.setText("Antes de iniciar, cadastre o Operador:");

        jButtonCadastrarOperador.setText("Cadastrar Operador");
        jButtonCadastrarOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarOperadorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ravie", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Game Locadora");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCadastrarOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                                .addGap(530, 530, 530))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButtonCadastrarOperador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jMenu1.setText("Arquivo");

        jMenuItemAdicionarOperador.setText("Cadastrar Operador");
        jMenuItemAdicionarOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdicionarOperadorActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAdicionarOperador);

        jMenuItemTrocarOperador.setText("Trocar Operador");
        jMenuItemTrocarOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTrocarOperadorActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTrocarOperador);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clientes");

        jMenuItemCadastrarCliente.setText("Adicionar");
        jMenuItemCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCadastrarCliente);

        jMenuItemRemoverCliente.setText("Buscar/Remover");
        jMenuItemRemoverCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRemoverClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRemoverCliente);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Jogos");

        jMenu6.setText("Cadastrar");

        jMenuItemCadastrarJogos.setText("Jogos");
        jMenuItemCadastrarJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarJogosActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemCadastrarJogos);

        jMenu3.add(jMenu6);

        jMenuItemBuscarJogos.setText("Buscar/Remover");
        jMenuItemBuscarJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarJogosActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemBuscarJogos);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Locação");

        jMenuItemLocacao.setText("Locação de Jogos");
        jMenuItemLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLocacaoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemLocacao);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAdicionarOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdicionarOperadorActionPerformed
       TelaCadastroFuncionario telaCadFuncionario = new TelaCadastroFuncionario();
       jDesktopPane.add(telaCadFuncionario);
       centralizaForma(telaCadFuncionario);

       telaCadFuncionario.setGame(GamePrincipal);

       telaCadFuncionario.setVisible(true);

    }//GEN-LAST:event_jMenuItemAdicionarOperadorActionPerformed

    private void jMenuItemTrocarOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTrocarOperadorActionPerformed
       TelaCadastroFuncionario telaCadFuncionario = new TelaCadastroFuncionario();
       jDesktopPane.add(telaCadFuncionario);
       centralizaForma(telaCadFuncionario);

       telaCadFuncionario.setGame(GamePrincipal);

       telaCadFuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuItemTrocarOperadorActionPerformed

    private void jMenuItemCadastrarJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarJogosActionPerformed
       TelaCadastroJogos telaCad = new TelaCadastroJogos();
       jDesktopPane.add(telaCad);
       centralizaForma(telaCad);

       telaCad.setGame(GamePrincipal);

       telaCad.setVisible(true);

       GamePrincipal.imprimeArrayJogos();


    }//GEN-LAST:event_jMenuItemCadastrarJogosActionPerformed

    private void jMenuItemCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarClienteActionPerformed
       TelaCadastroCliente telaCadCliente = new TelaCadastroCliente();
       jDesktopPane.add(telaCadCliente);
       centralizaForma(telaCadCliente);

       telaCadCliente.setGame(GamePrincipal);

       telaCadCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarClienteActionPerformed

    private void jMenuItemBuscarJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarJogosActionPerformed
       BuscarRemoverJogos telaBuscar = new BuscarRemoverJogos();
       jDesktopPane.add(telaBuscar);
       centralizaForma(telaBuscar);

       telaBuscar.setGame(GamePrincipal);

       telaBuscar.setVisible(true);
    }//GEN-LAST:event_jMenuItemBuscarJogosActionPerformed

    private void jMenuItemRemoverClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRemoverClienteActionPerformed
       BuscarRemoverPessoa telaRemPessoa = new BuscarRemoverPessoa();
       jDesktopPane.add(telaRemPessoa);
       centralizaForma(telaRemPessoa);

       telaRemPessoa.setGame(GamePrincipal);

       telaRemPessoa.setVisible(true);

    }//GEN-LAST:event_jMenuItemRemoverClienteActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLocacaoActionPerformed

        if(GamePrincipal.getOperador().getNome() == null){

            JOptionPane.showMessageDialog(null ,"Cadastre um operador primeiro!");
        }
        else{
        TelaLocacao telaLocar = new TelaLocacao();
        jDesktopPane.add(telaLocar);
        centralizaForma(telaLocar);

        telaLocar.setGame(GamePrincipal);


        telaLocar.setVisible(true);
        }

    }//GEN-LAST:event_jMenuItemLocacaoActionPerformed

    private void jButtonCadastrarOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarOperadorActionPerformed
        TelaCadastroFuncionario telaCadFuncionario = new TelaCadastroFuncionario();
        jDesktopPane.add(telaCadFuncionario);
        centralizaForma(telaCadFuncionario);

        telaCadFuncionario.setGame(GamePrincipal);

        telaCadFuncionario.setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarOperadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //Sivil principal = new Sivil();


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipal().setVisible(true);
        });
    }
    private void centralizaForma(JInternalFrame frame){
       Dimension desktopSize = jDesktopPane.getSize();
       Dimension jInternalFrameSize = frame.getSize();
       frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
               (desktopSize.height - jInternalFrameSize.height) / 2);
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarOperador;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAdicionarOperador;
    private javax.swing.JMenuItem jMenuItemBuscarJogos;
    private javax.swing.JMenuItem jMenuItemCadastrarCliente;
    private javax.swing.JMenuItem jMenuItemCadastrarJogos;
    private javax.swing.JMenuItem jMenuItemLocacao;
    private javax.swing.JMenuItem jMenuItemRemoverCliente;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemTrocarOperador;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
